### ISSUE TITLE
Desert Temple

### ISSUE THREAD

**Issue by SinlesFlyer376** [Muqsit/Structure#2]
so if I do /deserttemple it will make a desert temple automatically? If so, then please make To where I can confirm it with /dt confirm??

**Comment by SinlesFlyer376** [comment]
Also, don't you need to make at the end of a case "deserttemple": with a ; instead?

**Comment by SinlesFlyer376** [comment]
you didn't answer my questions lol

**Comment by Muqsit** [comment]
http://php.net/manual/en/control-structures.switch.php
